### ISSUE TITLE
Move signing functionality from `ethcontract` upstream.

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/ethcontract-rs#14]
Offline signing support has recently been added to `rust-web3`. We should use it instead of our custom code.

**Comment by nlordell** [comment]
Pull request is here tomusdrw/rust-web3#279

**Comment by gakonst** [comment]
Note that this was indeed merged but was later reverted due to license incompatibility

**Comment by nlordell** [comment]
New PR with license compatible crate: tomusdrw/rust-web3#325
