### ISSUE TITLE
Converting of error messages

### ISSUE THREAD

**Issue by josojo** [cowprotocol/ethcontract-rs#157]
Currently, error messages have a format like this one:
```
[web3 contract error: Api error: RPC error: Error { code: ServerError(-32015), message: "VM execution error.", data: Some(String("Reverted 0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001e536166654d6174683a207375627472616374696f6e206f766572666c6f770000")) }]
```

It would be great if the data could be converted from Hex to ASCII automatically.

If this task should not be provided from ethcontracts, then all other applications might have to code the conversion - us for example for the driver.

**Comment by fleupold** [comment]
This is already merged into master and part of the much longed for version bump!
