### ISSUE TITLE
[nit] ExecutionState variant naming

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/ethcontract-rs#20]
https://github.com/gnosis/ethcontract-rs/blob/24856c80af7bbc04b09f754cd9fc7249c8b486f3/src/transaction.rs#L520-L530

Build and Send sound somewhat imperative (as if the Future State is ready to be built/sent). In reality it is in the process of building/sending so maybe calling them building and sending instead is more expressive.

**Comment by nlordell** [comment]
Closed by #31
