### ISSUE TITLE
Remove runtime use of Artifact type

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/ethcontract-rs#209]
I think `ethcontract` should create its own runtime representation of contract data instead of using the Truffle artifact representation. I think it would look something like this:
```
struct Contract {
    pub name: String,
    pub abi: Abi,
    pub deployments: HashMap<String, Address>,
}
```

Doing this would also allow us to distinguish between what is needed at runtime (contract ABI and networks map) and what is additionally needed at generation time (documentation). Doing this could also simplify some of the contract traits that are currently needed for linking, fetching the deployed contract for a network, and new deployments as they could all operate over this runtime representation.

**Comment by taminomara** [comment]
`Artifact` was renamed to `Contract` in #512. Is there anything else that we want to do here?

**Comment by nlordell** [comment]
Yeah, lets close this.
