### ISSUE TITLE
InvalidResponse when calling function with large U256 parameter

### ISSUE THREAD

**Issue by e00E** [cowprotocol/ethcontract-rs#216]
Not sure if this error is in ethcontract or web3 is and didn't yet have time to look into this in more detail but posting anyway so I don't forget.

When playing around with the dex-service ganache e2e test I noticed that when I change the desposit amount in this line https://github.com/gnosis/dex-services/blob/v0.1.5/e2e/tests/stablex_test.rs#L33 to something like `let value: u128 = std::u64::MAX as u128 * 100;` the call errors:

```rust
MethodError { signature: "deposit(address,uint256)", inner: Web3(InvalidResponse("Error(\"data did not match any variant of untagged enum Response\", line: 0, column: 0)")) }
```

The initial error message comes from serde_derive. The error doesn't start appearing at exactly the u64 max boundary.

**Comment by nlordell** [comment]
This might be a Ganache thing as well. Ganache has a feature that when transactions would fail, it returns the transaction hash and the revert error in the same response. This causes a JSON parse error as it cannot distinguish between the `Success` and `Failure` variants. You can enable verbose logs in Ganache and see if that is he case.

If this is the case I would argue it is a Ganache issue as the JSON RPC v2 spec doesn’t allow this kind of response.

We should check against this in the new HTTP transport but there might be a bug in that code as it hasn’t particularly been stressed.

**Comment by e00E** [comment]
The larger parameter was unrelated. The transaction correctly reverted, we just got a weird error message which as you say can be a bug in Ganache.

**Comment by nlordell** [comment]
@e00E can you open this case in dex-services as the new HTTP transport should be able to handle this case but it appears that it isn’t.

Here is the code that appears to not be working https://github.com/gnosis/dex-services/blob/3ae7584c476f16e43eecf46e3aaddbee3759897f/driver/src/transport.rs#L91
