### ISSUE TITLE
Support ViewMethod batching

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/ethcontract-rs#355]
When doing successive RPC calls a major speedup can be achieved by using BatchedTransport and executing multiple requests in a single roundtrip. 

At the moment BatchTransport is not well supported by ethcontract-rs. Creating a new instance with batched transport is cumbersome as we have to flush it before we can successfully await the instance (with a risk of deadlock)

```rust
let instance_future = Instance::deployed(&batched_transport); // if we await here we deadlock since deployed requires to make a RPC call
batched_transport.submit_batch.await;
let instance = instance_future.await;
``` 

I also ran into issues executing calls on this batched transport instance. Since call futures are lazily initialized, we need to poll them once before they enqueue their RPC requests onto the batched transport. Only then can we flush the batched transport and afterwards await the original futures.

A better more integrated approach to support batching would probably involve making it part of a separate API. This API could probably be limited to ViewMethods, as "real" transactions don't really gain that much from being batched on the transport layer (confirmation is usually much longer than roundtrip time, no guarantees that batched txs end up in same block, dependent RPC calls e.g. to estimate gas_limit/gas_price might be necessary).

My suggestion would be to expose a `call_in_batch(batch_transport)` method on ViewMethodBuilder which instead of calling `self.web3.eth().call(...)` would invoke `batch_transport.eth().call(...)` and would return a future that as soon as polled, first awaits the `batch_transport.submit_batch()` future which should ensure that the original request (that was enqueued in the batch transport) can be polled afterwards. At the same time it allows customers to collect multiple calls before awaiting on the results.

We could also make the customer responsible for calling `batch_transport.submit_batch()`, however my worry would be that this could lead to deadlocks if one awaits a call before awaiting `submit_batch()`.

**Comment by taminomara** [comment]
I think this issue is implemented and can be closed.
