### ISSUE TITLE
Add support for solc 0.6

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/ethcontract-rs#360]
Currently, support for solc 0.6 is not great. Specifically, the ABI JSON format has changed and not supported by `ethabi` crate.

**Comment by taminomara** [comment]
Is there any more incompatibilities besides #546?

**Comment by nlordell** [comment]
I think this can be closed. I also don't see a good way to work around conflating `fallback` and `receive` at a type level. Happy to hear if you have any ideas.

**Comment by taminomara** [comment]
> I also don't see a good way to work around conflating fallback and receive at a type level. Happy to hear if you have any ideas.

No ideas right now. I'm not sure if we need the distinction tbh.
