### ISSUE TITLE
Update web3 to 0.14

### ISSUE THREAD

**Issue by lsunsi** [cowprotocol/ethcontract-rs#426]
I added this since I'm using both of these packages and I wanted to upgrade on mine project. (:
Thankfully the update was straight forward enough and one attempt at it can be seen at #425

**Comment by nlordell** [comment]
We just released a new version of ethcontract to crates.io with `web3 v0.15` :tada: 

If you need a release specifically for `web3 v0.14` feel free to re-open the issue.
