### ISSUE TITLE
Move deployment logic from travis to github actions

### ISSUE THREAD

**Issue by e00E** [cowprotocol/ethcontract-rs#436]
Just a reminder for us. The github actions PR only moved the tests but not the deployment so this is atm still handled by travis.

**Comment by taminomara** [comment]
I see `release.yaml` workflow, and I don't see any travis config. Is this issue still relevant?

**Comment by nlordell** [comment]
Looks like it can be closed: https://github.com/gnosis/ethcontract-rs/actions/workflows/release.yaml

**Comment by nlordell** [comment]
We have successful deployments with it already.
