### ISSUE TITLE
Add `(View)MethodBuilder::encode_abi()` Method

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/ethcontract-rs#58]
This would ABI encode the method with parameters. It would generate the `data` for a transaction so that it can be used in other ways.

**Comment by e00E** [comment]
It seems we have generated the data already in the constructor:

```
pub fn new(web3: Web3<T>, function: Function, address: Address, data: Bytes) -> Self
```

Is this just a matter of making this data accessible again or is there something more needed that I am missing?
If its the first case then would it be cleaner to have this directly on `Instance` so there is no need to go through the `MethodBuilder`?

**Comment by nlordell** [comment]
I think this is a leftover case from before. Right now you can `method.tx.data` to access the ABI encoded parameters.

I'm going to close this for now.
