### ISSUE TITLE
Update Cargo `web3` dependency before publishing

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/ethcontract-rs#643]
We needed to use a git dependency of `web3` for the moment. We need to update to `crates.io` released version before publishing a new version to `crates.io` ourselves.

**Comment by vkgnosis** [comment]
I was confused about this at first but I think you are referring to the gp-v2-services repository which has a web3 git dependency but not ethcontract.

**Comment by vkgnosis** [comment]
I see. We have a branch created by https://github.com/gnosis/ethcontract-rs/pull/646 that has the git dependency and PR also wants it https://github.com/gnosis/ethcontract-rs/pull/638 .

**Comment by sunce86** [comment]
I think this was resolved with updating to web3 v0.18 https://github.com/gnosis/ethcontract-rs/pull/718
