### ISSUE TITLE
Incorrect event type

### ISSUE THREAD

**Issue by josojo** [cowprotocol/ethcontract-rs#867]
The repo created from the abis from [here](https://raw.githubusercontent.com/cowprotocol/ethflowcontract/v0.0.0-rc.1-artifacts/artifacts/CoWSwapEthFlow.sol/CoWSwapEthFlow.json) the following code:
```
pub mod event_data {
        use super::ethcontract;
        #[derive(Clone, Debug, Default, Eq, PartialEq)]
        pub struct OrderInvalidation {
            pub order_uid: self::ethcontract::H256,
        }
        impl OrderInvalidation {
            #[doc = r" Retrieves the signature for the event this data corresponds to."]
            #[doc = r" This signature is the Keccak-256 hash of the ABI signature of"]
            #[doc = r" this event."]
            pub fn signature() -> self::ethcontract::H256 {
                self::ethcontract::H256([
                    184, 186, 209, 2, 172, 139, 186, 207, 239, 49, 255, 28, 144, 110, 198, 217, 81,
                    194, 48, 180, 220, 231, 80, 187, 3, 118, 184, 18, 173, 53, 133, 42,
                ])
            }
            #[doc = r" Retrieves the ABI signature for the event this data corresponds"]
            #[doc = r" to. For this event the value should always be:"]
            #[doc = r""]
            #[doc = "`OrderInvalidation(bytes)`"]
            pub fn abi_signature() -> &'static str {
                "OrderInvalidation(bytes)"
            }
        }
   ```
Note that it says: 
```
 "OrderInvalidation(bytes)"
 but we get order_uid: H256
```

I looked it up and I found the problematic line:
https://github.com/gnosis/ethcontract-rs/blob/03278a46304aa68a36fd46c8fa924b5506029dbb/ethcontract-generate/src/generate/events.rs#L522

I can not make any sense out of the comment :( 
why is it different for indexes? How can I fix it? Obviously, I need the whole 56 bytes and not just the first 32.

cc: @nlordell

**Comment by nlordell** [comment]
Indexed log fields that are larger than 32 bytes (like a dynamic byte array) don't actually encode themselves in the log data at all (only their hash as an indexed field). If you want to index it AND have the data, you need to include it twice (once indexed and once not).

**Comment by josojo** [comment]
>You can add the attribute indexed to up to three parameters which adds them to a special data structure known as [“topics”](https://docs.soliditylang.org/en/latest/abi-spec.html#abi-events) instead of the data part of the log. A topic can only hold a single word (32 bytes) so if you use a [reference type](https://docs.soliditylang.org/en/latest/types.html#reference-types) for an indexed argument, the Keccak-256 hash of the value is stored as a topic instead.

https://docs.soliditylang.org/en/latest/contracts.html#events

Nick is right! Ups, we have to redeploy
