### ISSUE TITLE
Turn Builder into a Future which builds underlying default future on first poll

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/ethcontract-rs#98]
Right now, we need to call a method on the builder in order to turn it into a future. E.g. for a transaction, we need to invoke `.send()` in order to turn its MethodBuilder into a SendFuture.

A less verbose approach could be to have the builder itself be a future and upon first poll build and drive the underlying (default) SendFuture. If someone wanted to *call* a non-view method (e.g. to check if execution is likely to succeed), they could still explicitly turn it into a `CallFuture` by invoking `.call()` on the builder.

This would save one line of boilerplate code in the majority of the cases (e.g. deploy & call can only ever be invoked with one type of Future).

**Comment by e00E** [comment]
Looking at `Transaction` `send` does more than just create a `SendFuture`: it also consumes `self`. This means that after the call you can no longer change parameters of the builder and this is enforced by the type system.
If `Transaction` itself is a `SendFuture` then you cannot prevent users from trying to change parameters after `send`. It would either have no effect or would panic.
I prefer the current behavior.

We could skip the `MethodBuilder` and pass the parameters directly to `transact` using a struct that implements `std::default::Default`. In general, it seems like most builders could be replaced with struct + default. Not sure how other crates handle this.

**Comment by nlordell** [comment]
Personally I'm a fan of the builder pattern (and it seems to be pretty idiomatic in the Rust world). @e00E is correct that currently the type system enforces that a `TransactionBuilder` cannot be changed after builds its future. Personally I like this as well.

I think this could be split into 2 parts:
1) Define some `IntoFuture` trait and have builders implement it.
2) Refactor the `FutureWaitExt` trait from `dex-services` into something that takes an `IntoFuture` and have it call `into_future().wait()`.

It might even make sense to put both of these into `dex-services`.

**Comment by nlordell** [comment]
@fleupold Are you OK with closing this in favour of gnosis/dex-services#459?

**Comment by fleupold** [comment]
Yes
